'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Sparkles, Code2, Globe, BrainCircuit, Copy, Route, MapPin, Trophy, Check, Zap, Command } from 'lucide-react';
const events = [
 {name:'Neuralysis',tag:'AI IMAGE GENERATION',icon:Sparkles,color:'#c3a6ff',description:'A picture. Your prompt. A whole new perspective.',detail:'Study the photo provided by the event head, then write a detailed prompt in GPT 5.0 to recreate it as closely as possible.',skill:'Prompt • Generate • Recreate'},
 {name:'Hackathon',tag:'AI WEBSITE BUILDING',icon:Globe,color:'#a9f26d',description:'Big ideas deserve more than a blank screen.',detail:'Build a website around your own idea on a topic chosen by the event head. Use a website creation AI and turn your prompt into a working experience.',skill:'Imagine • Prompt • Build'},
 {name:'SyntaxShowdown',tag:'PROGRAMMING',icon:Code2,color:'#80caff',description:'Your language. Your logic. Your time to shine.',detail:'Solve programming questions set by the event head in any programming language of your choice. Bring your problem-solving skills.',skill:'Think • Code • Solve'},
 {name:'InfoWiz',tag:'IT QUIZ',icon:BrainCircuit,color:'#ffbf75',description:'Put your tech knowledge in the spotlight.',detail:'Take on an IT quiz organised and led by the event head. Test your knowledge and discover something new along the way.',skill:'Recall • Connect • Answer'},
 {name:'The Copycat Blueprint',tag:'AI WEBSITE RECREATION',icon:Copy,color:'#ffa1bc',description:'Spot the details. Decode the design. Rebuild it.',detail:'Examine the reference website provided by the event head. Describe its layout and details in Bolt AI to recreate the original as faithfully as possible.',skill:'Observe • Describe • Recreate'},
 {name:'WikiThon',tag:'WIKIPEDIA CHALLENGE',icon:Route,color:'#78ded2',description:'Two words. Countless paths. Find your way.',detail:'Navigate from an origin article to a destination article chosen by the event head, using only Wikipedia’s blue hyperlinks to reach your target.',skill:'Explore • Link • Discover'},
];
export default function Home(){
 const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [receipt,setReceipt]=useState('');
 function toggle(name:string){setError('');setSelected(v=>v.includes(name)?v.filter(x=>x!==name):v.length<2?[...v,name]:v);}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'select_competitions',description:'Select competitions in the registration form. Does not submit registration.',inputSchema:{type:'object',properties:{events:{type:'array',items:{type:'string',enum:events.map(e=>e.name)},minItems:1,maxItems:2,uniqueItems:true}},required:['events'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!Array.isArray(input?.events)||!input.events.length||input.events.length>2||input.events.some((n:unknown)=>!events.some(e=>e.name===n)))throw new Error('Choose one or two valid competitions');setSelected([...new Set(input.events)] as string[]);document.getElementById('register')?.scrollIntoView();return {selected:input.events,submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!selected.length||selected.length>2){setError('Choose one or two competitions to continue.');return;}setBusy(true);const data=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,events:selected})});const result=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(result.error||'Registration could not be saved. Please try again.');setReceipt(result.id);}catch(err){setError(err instanceof Error?err.message:'Please try again.');}finally{setBusy(false);}}
 return <><header><a className="brand" href="#"><img className="event-logo" src="/matrix-unbounded.jpeg" alt="" width="44" height="46"/><span>MATRIX<span className="brand-sub">UNBOUNDED</span></span></a><nav><a href="#about">The experience</a><a href="#events">Explore events</a><a className="nav-cta" href="#register">Register now <ArrowUpRight size={17}/></a></nav></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> OUR FIRST-EVER TECH & AI EVENT</div><h1>Matrix<br/><span className="italic">Unbounded.</span></h1><p className="event-tagline">Beyond limits. Beyond reality.</p><p className="hero-description">Think beyond the classroom. Build with AI, put your skills to the test, and discover what you’re capable of.</p><div className="hero-buttons"><a href="#register" className="button primary">Enter the arena <ArrowUpRight size={20}/></a><a href="#events" className="button secondary">Explore the events <ArrowRight size={18}/></a></div><div className="hero-meta"><span><MapPin size={16}/> Kolkata, India</span><span className="divider"/><span>Presented by Advantage Academic Centre</span></div></div>
 <div className="event-art"><img src="/matrix-unbounded.jpeg" alt="Matrix Unbounded — Beyond limits. Beyond reality. Official event artwork with glowing green digital code." width="1080" height="1120" fetchPriority="high"/></div></section>
 <div className="ticker"><span>CREATE SOMETHING NEW</span><span>✳</span><span>CHALLENGE YOURSELF</span><span>✳</span><span>WIN AMAZING PRIZES</span><span>✳</span><span>EXPLORE THE POSSIBLE</span><span>✳</span></div>
 <section id="about" className="about section"><div><div className="eyebrow muted">A FIRST FOR ADVANTAGE. A NEXT STEP FOR YOU.</div><h2>A little curiosity.<br/>A lot of <span className="green">potential.</span></h2></div><div className="about-copy"><p>Advantage Academic Centre, Kolkata, is bringing technology out of the textbook and into your hands. Join Matrix Unbounded, our first-ever tech and AI event, to learn, explore, and compete.</p><div className="perks"><span><Zap/> Learn by doing</span><span><Trophy/> Compete for prizes</span></div></div></section>
 <section id="events" className="section events"><div className="section-heading"><div><div className="eyebrow muted">FIND YOUR CHALLENGE</div><h2>Six events. <span className="dim">Infinite possibilities.</span></h2></div><span className="count-label">01—06 / THE LINEUP</span></div><div className="event-grid">{events.map((event,i)=><article className="event-card" key={event.name} style={{'--event-color':event.color} as React.CSSProperties}><div className="card-top"><span className="event-icon"><event.icon size={25}/></span><span className="event-number">0{i+1}</span></div><span className="event-tag">{event.tag}</span><h3>{event.name}</h3><p className="event-intro">{event.description}</p><p className="event-detail">{event.detail}</p><div className="card-bottom"><span>{event.skill}</span><a href="#register" onClick={()=>{if(!selected.includes(event.name)&&selected.length>=2){setError('You have selected two events. Deselect one to choose a different event.');return;}setSelected(v=>v.includes(event.name)?v:[...v,event.name]);}} aria-label={`Register for ${event.name}`}><ArrowUpRight size={22}/></a></div></article>)}</div></section>
 <section className="prize-banner"><div className="prize-icon"><Trophy size={42}/></div><div><div className="eyebrow">BRING YOUR BEST. TAKE HOME MORE.</div><h2>Great ideas deserve <span className="italic">amazing prizes.</span></h2><p>Learn something new. Make your mark. Compete to win.</p></div><span className="prize-note">Prize details<br/>to be announced <Sparkles size={18}/></span></section>
 <section className="section registration" id="register"><div className="registration-copy"><div className="eyebrow muted">YOUR NEXT BIG THING STARTS HERE</div><h2>Ready to<br/>make your <span className="green italic">move?</span></h2><p>Bring your curiosity. We’ll bring the challenge.<br/>Choose up to two events and register your interest.</p><div className="info-row"><MapPin/><div><strong>Kolkata</strong><span>Exact venue to be announced</span></div></div><div className="info-row"><Zap/><div><strong>The first edition</strong><span>Event date and timings to be announced</span></div></div><div className="organizer-note">ORGANISED BY<strong>Advantage Academic Centre</strong><span>Learn. Explore. Get ahead.</span></div></div>
 <div className="form-card">{receipt?<div className="success" role="status"><span className="success-icon"><Check size={32}/></span><h3>You’re on the list!</h3><p>Your registration has been saved for {selected.join(', ')}.</p><p>Keep your reference: <strong>{receipt}</strong></p><p>Event date, venue, and participation details are still to be announced.</p><button className="button secondary" onClick={()=>{setReceipt('');setSelected([]);}}>Register another participant</button></div>:<form onSubmit={submit}><div className="form-title"><h3>Save your spot</h3><span>LET’S DO THIS <ArrowUpRight size={16}/></span></div><p className="form-sub">A few details, and you’re one step closer.</p><div className="fields"><label>Full name<input name="name" autoComplete="name" placeholder="Your full name" required maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></label><label>Mobile number<input name="phone" type="tel" autoComplete="tel" placeholder="10-digit mobile number" pattern="(?:\+91[ -]?)?[6-9][0-9]{9}" required title="Enter a 10-digit Indian mobile number, optionally prefixed with +91"/></label><label>School / institution<input name="institution" placeholder="Where do you study?" required maxLength={150}/></label></div><fieldset><legend>Choose your events <span>{selected.length}/2 selected</span></legend><p className="selection-help">Choose one or two events. Deselect an event to change your selection.</p><div className="event-options">{events.map(event=><label className={selected.includes(event.name)?'option selected':'option'} key={event.name}><input type="checkbox" disabled={busy||(!selected.includes(event.name)&&selected.length>=2)} checked={selected.includes(event.name)} onChange={()=>toggle(event.name)}/>{event.name}</label>)}</div></fieldset><label className="consent"><input type="checkbox" name="consent" required/>I agree to share these details with Advantage Academic Centre for event registration and communication.</label>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary submit" disabled={busy}>{busy?'Saving your registration…':'Register now'}<ArrowUpRight size={20}/></button><p className="form-foot">Your next chapter in tech starts with a little curiosity.</p></form>}</div></section></main><footer><a className="brand" href="#"><span className="brand-symbol"><Command size={21}/></span><span>ADVANTAGE<span className="brand-sub">ACADEMIC CENTRE</span></span></a><span>Made for curious minds. Kolkata, India.</span><a href="#events">Explore. Create. Compete. <ArrowUpRight size={16}/></a></footer></>;
}

